// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projFront.Data;

#nullable disable

namespace projFront.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240626131535_Identidade")]
    partial class Identidade
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.31");
#pragma warning restore 612, 618
        }
    }
}
